{
    "comments": [
        {
            "start": {
                "row": 2,
                "column": 40
            },
            "text": "# broken symlink pointing to itself"
        },
        {
            "start": {
                "row": 1,
                "column": 30
            },
            "text": "# fix for bpo-35306"
        },
        {
            "start": {
                "row": 0,
                "column": 26
            },
            "text": "# drive exists but is not accessible"
        }
    ],
    "deleted_lines": [
        0,
        1,
        2
    ],
    "commit_sha": "b6135f0011d27ce063557dd96fe003b71f7c9b97",
    "file_name": "/home/cvaniak/Code/Cvaniak/Consistent/poc/tests/cases/unknown_problem_1/with_comments.py"
}
